# Generated by Django 5.0.6 on 2024-07-03 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='service',
            field=models.CharField(choices=[], default='bruh', max_length=225),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctor',
            name='photo',
            field=models.ImageField(default='default-avatar.jpeg', upload_to='doctors'),
        ),
        migrations.AlterField(
            model_name='service',
            name='photo',
            field=models.ImageField(upload_to='services'),
        ),
    ]
